### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by Mte90** [abhinavxd/yt-chat-archive#4]
So I am getting:
```
panic: runtime error: index out of range [0] with length 0

goroutine 8 [running]:
github.com/abhinavxd/youtube-live-chat-downloader/v2.ParseInitialData({_, _})
        /home/mte90/go/pkg/mod/github.com/abhinavxd/youtube-live-chat-downloader/v2@v2.0.1/yt_chat.go:259 +0x446
cli-stream-chat/pkg/provider.(*Youtube).Listen(0x8eb868, 0xc0000163e0, {0x7ffd0c49f6e2, 0x2b}, {0xc000070300, 0x3, 0x4}, 0xc000024180)
        /home/mte90/Desktop/kde/cli-stream-chat/pkg/provider/youtube.go:15 +0x66
created by main.runListeners
        /home/mte90/Desktop/kde/cli-stream-chat/chat.go:26 +0x21a
exit status 2
```

My guess is that the regex is not working and return null https://github.com/abhinavxd/youtube-live-chat-downloader/blob/main/yt_chat.go#L141

Ref: https://github.com/blacktrub/cli-stream-chat/issues/1

**Comment by Mte90** [comment]
Investigating a bit the regex works but the issue is that the request in reality is blocked and require to resolve a captcha.
So probably youtube is detecting the tool not as a browser and the content is broken.

**Comment by Mte90** [comment]
I was able to get the output using cookies.
I did with a new aninymous window the same url, complete the captcha and with 4 cookies now I get something:

* CONSENT
* PREF
* goojf
* __Secure-3PSIDCC

So probably this library need a way to share the cookies for the youtube request to avoid the 429 error.

**Comment by Mte90** [comment]
```
func ParseInitialData(videoUrl string) (string, YtCfg, error) {
	req, err := http.NewRequest("GET", videoUrl, nil)
	cookie := &http.Cookie{
		Name:   "CONSENT",
		Value:  "YES+yt.432048971.it+FX+446",
		MaxAge: 300,
	}
	req.AddCookie(cookie)
	cookie2 := &http.Cookie{
		Name:   "PREF",
		Value:  "tz=Europe.Rome",
		MaxAge: 300,
	}
	req.AddCookie(cookie2)
	cookie3 := &http.Cookie{
		Name:   "goojf",
		Value:  "[content]",
		MaxAge: 300,
	}
	req.AddCookie(cookie3)
	cookie4 := &http.Cookie{
		Name:   "__Secure-3PSIDCC",
		Value:  "[content]",
		MaxAge: 300,
	}
	req.AddCookie(cookie4)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", YtCfg{}, err
	}

	defer resp.Body.Close()
// added that block to get the error
	if resp.StatusCode != 200 {
		fmt.Print(videoUrl +
		"\nresp.StatusCode: " + strconv.Itoa(resp.StatusCode))
		return "", YtCfg{}, err
	}

	intArr, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return "", YtCfg{}, err
	}

	html := string(intArr)

	// TODO ::  work on regex
	initialDataArr := regexSearch(INITIAL_DATA_REGEX, html)
	initialData := strings.Trim(string(initialDataArr[0]), "ytInitialData = ") // added string here
	initialData = strings.Trim(initialData, ";</script")
	ytCfg := regexSearch(YT_CFG_REGEX, html)[0]
	ytCfg = strings.Trim(ytCfg, "ytcfg.set(")
	ytCfg = strings.Trim(ytCfg, ");")

	var _ytCfg YtCfg
	json.Unmarshal([]byte(ytCfg), &_ytCfg)

	var _initialData InitialData
	json.Unmarshal([]byte(initialData), &_initialData)

	subMenuItems := _initialData.Contents.TwoColumnWatchNextResults.ConversationBar.LiveChatRenderer.Header.LiveChatHeaderRenderer.ViewSelector.SortFilterSubMenuRenderer.SubMenuItems
	initialContinuationInfo := subMenuItems[1].Continuation.ReloadContinuationData.Continuation
	return initialContinuationInfo, _ytCfg, nil
}
```

Also if the URL is not from a live the library crash as doesn't find the parameters in the JSON that is parsing without giving any hints.

**Comment by abhinavxd** [comment]
hey, thanks!
Fixing this.

**Comment by abhinavxd** [comment]
I have merged the fix and added `CONSENT` & `PREF` cookies to request.

I guess that will work?  
I could not recreate the 429 error.

**Comment by Mte90** [comment]
On my tests it wasn't enough and required also the other 2 cookies.
I tried also now with my previous code and I am getting again 429 with those values so probably I need to update the cookie again.

**Comment by Mte90** [comment]
So I tested again and consent and pref are not enough cookie values.
I guess that are required more cookie values...

**Comment by Mte90** [comment]
It is possible to create a file with the cookie content? like in `tmp/yt-cookies.txt` so can load it without altering the code?
Or to provide the HTML page downloaded by the browser of the live streaming?

**Comment by abhinavxd** [comment]
I was thinking of 
modifying `ParseInitialData` function. Will add one more parameter named `customCookies`
So anyone calling this function will be able to add/override the cookies.

Providing an HTML page content & txt file also sounds good, I will look into this as well

**Comment by abhinavxd** [comment]
I've added a new function `AddCookies`,
You can pass multiple cookies to this function.
